# Override engine version for hosts in the [engine_testing] inventory group.
# Update these values to point to the testing engine release.
engine_github_path: https://github.com/beyond-all-reason/RecoilEngine/releases/download/2026.07.03/recoil_2026.07.03_amd64-linux.7z
engine_dir: recoil_2026.07.03_amd64-linux
