---
- name: Stop SPADS
  hosts: all
  become: yes

  tasks:
    - name: Stop and disable SPADS timers and services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - pr-downloader.timer
        - spads_config_updater.timer
        - pr-downloader.service
        - spring-setcpuaffinity.service
        - spads_config_updater.service
        - map_syncer.service
        - clear_rapid_packages.timer
        - clear_replays.timer

    - name: Stop and disable SPADS
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
        - spads.service
